//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD_APLICACION
    {
        public ACTIVIDAD_APLICACION()
        {
            this.PERFIL = new HashSet<PERFIL>();
        }
    
        public int CODIGO_ACTIVIDAD_APLICACION { get; set; }
        public string NOMBRE { get; set; }
        public string URL { get; set; }
        public Nullable<int> COD_MODULO_APLICACION { get; set; }
    
        public virtual MODULO_APLICACION MODULO_APLICACION { get; set; }
        public virtual ICollection<PERFIL> PERFIL { get; set; }
    }
}
