//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOXNOMINACIONXCRITERIO
    {
        public int ARCHIVOXNOMINACIONXCRITERIOS { get; set; }
        public string URL_ARCHIVO { get; set; }
        public string DESCRIPCION_ARCHIVO { get; set; }
        public Nullable<int> COD_NOMINACION_CRITERIO_EXCLUYENTE { get; set; }
    }
}
