//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOXPROCESO
    {
        public int COD_ARCHIVOXPROCESO { get; set; }
        public Nullable<int> VIGENCIA { get; set; }
        public string SECCION { get; set; }
        public string SUBSECCION { get; set; }
        public string TEXTO { get; set; }
        public string URL { get; set; }
        public Nullable<int> COD_PROCESO { get; set; }
    
        public virtual PROCESO PROCESO { get; set; }
    }
}
