//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOXNOMINACION
    {
        public int COD_ARCHIVOXNOMINACION { get; set; }
        public string URL_ARCHIVO { get; set; }
        public string DESCRIPCION_ARCHIVO { get; set; }
        public int COD_NOMINACION_PROCESO { get; set; }
    
        public virtual NOMINACION_PROCESO NOMINACION_PROCESO { get; set; }
    }
}
