//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION_VALIDACION_PROCESO
    {
        public int COD_CONFIGURACION_VALIDACION_PROCESO { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<bool> VALIDA_MEDICAMENTO { get; set; }
        public Nullable<bool> VALIDA_PROCEDIMIENTO { get; set; }
        public Nullable<bool> VALIDA_OTRO { get; set; }
        public Nullable<bool> VALIDA_DISPOSITIVO_MEDICO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
