//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIRMACION_EVENTO
    {
        public CONFIRMACION_EVENTO()
        {
            this.CONFIRMACION_EVENTO1 = new HashSet<CONFIRMACION_EVENTO>();
            this.FORMATOEVENTOXCONFIRMACION = new HashSet<FORMATOEVENTOXCONFIRMACION>();
            this.TECNOLOGIAXCONFIRMACION_EVENTO = new HashSet<TECNOLOGIAXCONFIRMACION_EVENTO>();
        }
    
        public int COD_CONFIRMACION_EVENTO { get; set; }
        public Nullable<int> COD_EVENTO { get; set; }
        public Nullable<int> COD_REGISTRO { get; set; }
        public Nullable<bool> COMPLETO { get; set; }
        public Nullable<bool> CANCELADO { get; set; }
        public Nullable<System.DateTime> FECHA_CONFIRMACION { get; set; }
        public Nullable<System.DateTime> FECHA_COMPLETO { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public Nullable<int> COD_CONFIRMACION_EVENTO_PADRE { get; set; }
        public Nullable<bool> ASISTIO { get; set; }
    
        public virtual ICollection<CONFIRMACION_EVENTO> CONFIRMACION_EVENTO1 { get; set; }
        public virtual CONFIRMACION_EVENTO CONFIRMACION_EVENTO2 { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        public virtual REGISTRO REGISTRO { get; set; }
        public virtual ICollection<FORMATOEVENTOXCONFIRMACION> FORMATOEVENTOXCONFIRMACION { get; set; }
        public virtual ICollection<TECNOLOGIAXCONFIRMACION_EVENTO> TECNOLOGIAXCONFIRMACION_EVENTO { get; set; }
    }
}
