//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_OBJECION
    {
        public int COD_DETALLE_OBJECION { get; set; }
        public Nullable<int> COD_OBJECION_PROCESO { get; set; }
        public Nullable<int> COD_PARAMETRO_VALIDACION { get; set; }
        public Nullable<int> CONSECUTIVO { get; set; }
        public string DESCRIPCION_OBJECION { get; set; }
    
        public virtual OBJECION_PROCESO OBJECION_PROCESO { get; set; }
        public virtual PARAMETRO_VALIDACION PARAMETRO_VALIDACION { get; set; }
    }
}
