//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_NOMINACION
    {
        public ESTADO_NOMINACION()
        {
            this.NOMINACION_PROCESO = new HashSet<NOMINACION_PROCESO>();
        }
    
        public int COD_ESTADO_NOMINACION { get; set; }
        public string NOMBRE_ESTADO_NOMINACION { get; set; }
    
        public virtual ICollection<NOMINACION_PROCESO> NOMINACION_PROCESO { get; set; }
    }
}
