//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATOEVENTOXCONFIRMACION
    {
        public int COD_FORMATOEVENTOXCONFIRMACION { get; set; }
        public Nullable<int> COD_FORMATO_EVENTO { get; set; }
        public Nullable<int> COD_CONFIRMACION_EVENTO { get; set; }
        public string URL_ARCHIVO { get; set; }
    
        public virtual CONFIRMACION_EVENTO CONFIRMACION_EVENTO { get; set; }
        public virtual FORMATO_EVENTO FORMATO_EVENTO { get; set; }
    }
}
