//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATO_EVENTOXEVENTO
    {
        public int COD_FORMATO_EVENTOXEVENTO { get; set; }
        public int COD_EVENTO { get; set; }
        public int COD_FORMATO_EVENTO { get; set; }
        public bool APLICA_NATURAL { get; set; }
        public bool APLICA_JURIDICO { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual FORMATO_EVENTO FORMATO_EVENTO { get; set; }
    }
}
