//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_PARAMETRO_VALIDACION
    {
        public GRUPO_PARAMETRO_VALIDACION()
        {
            this.PARAMETRO_VALIDACION = new HashSet<PARAMETRO_VALIDACION>();
        }
    
        public int COD_GRUPO_PARAMETRO_VALIDACION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<PARAMETRO_VALIDACION> PARAMETRO_VALIDACION { get; set; }
    }
}
