//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoEliminacion
    {
        public int Id { get; set; }
        public string NumeroIdentificacion { get; set; }
        public System.DateTime FechaValidacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<short> IdTipoUsuario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public Nullable<short> IdTipoIdentificacion { get; set; }
        public Nullable<short> IdTipoIdentificacionRepresentante { get; set; }
        public string NumeroIdentificacionRepresentante { get; set; }
        public string PathNumeroIdentificacion { get; set; }
        public string PathConstitucionGrupo { get; set; }
        public string PatologiaAsociacion { get; set; }
        public string PathCertificacionPatologia { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<int> NumeroAsociados { get; set; }
        public string Direccion { get; set; }
        public string Genero { get; set; }
        public Nullable<bool> Certifico { get; set; }
        public Nullable<bool> Autorizo { get; set; }
        public string Contrasena { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<short> IdPreguntaSecreta { get; set; }
        public string RespuestaPregunta { get; set; }
        public Nullable<short> IdEstadoUsuario { get; set; }
        public Nullable<short> IdMunicipio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> AutorizoEmail { get; set; }
        public string ValorContrasena { get; set; }
        public string digitoVerificacionRepresentante { get; set; }
        public string digitoVerificacion { get; set; }
        public Nullable<int> ValidadoPor { get; set; }
        public Nullable<bool> pendiente_informacion { get; set; }
        public Nullable<bool> pendienteInformacion { get; set; }
    }
}
