//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENTOS
    {
        public string COD_MEDICAMENTOS { get; set; }
        public string NOMBRE_MEDICAMENTOS { get; set; }
        public bool HABILITADO_MIPRES { get; set; }
        public string VERSION_MIPRES { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
