//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO_APLICACION
    {
        public MODULO_APLICACION()
        {
            this.ACTIVIDAD_APLICACION = new HashSet<ACTIVIDAD_APLICACION>();
            this.PERFIL = new HashSet<PERFIL>();
        }
    
        public int COD_MODULO_APLICACION { get; set; }
        public string NOMBRE_MODULO_APLICACION { get; set; }
        public Nullable<short> ORDEN { get; set; }
    
        public virtual ICollection<ACTIVIDAD_APLICACION> ACTIVIDAD_APLICACION { get; set; }
        public virtual ICollection<PERFIL> PERFIL { get; set; }
    }
}
