//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_FORMACION
    {
        public NIVEL_FORMACION()
        {
            this.REGISTRO = new HashSet<REGISTRO>();
        }
    
        public int COD_NIVEL_FORMACION { get; set; }
        public string NIVEL_FORMACION1 { get; set; }
    
        public virtual ICollection<REGISTRO> REGISTRO { get; set; }
    }
}
