//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINACION_CRITERIO_EXCLUYENTE
    {
        public int COD_NOMINACION_EXCLUYENTE { get; set; }
        public int COD_REGISTRO { get; set; }
        public Nullable<int> COD_EXCLUSION { get; set; }
        public Nullable<System.DateTime> FECHA_NOMINACION { get; set; }
        public string OBSERVACIONES_NOMINACION { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_B { get; set; }
        public string DESC_EXCLUIDA_CRITERIO_B { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_C { get; set; }
        public string DESC_EXCLUIDA_CRITERIO_C { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_D { get; set; }
        public string DESC_EXCLUIDA_CRITERIO_D { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_E { get; set; }
        public string DESC_EXCLUIDA_CRITERIO_E { get; set; }
        public Nullable<bool> ADJUNTA_EVIDENCIA { get; set; }
        public string OBSERVACIONES_EVIDENCIA { get; set; }
        public Nullable<bool> CONFLICTO_INTERES { get; set; }
        public string OBSERVACIONES_CONFLICTO { get; set; }
        public Nullable<int> COD_ESTADO_NOMINACION { get; set; }
    }
}
