//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINACION_PROCESO_RUPS
    {
        public NOMINACION_PROCESO_RUPS()
        {
            this.VALIDACION_PROCESO_RUPS = new HashSet<VALIDACION_PROCESO_RUPS>();
        }
    
        public int COD_NOMINACION_PROCESO_RUPS { get; set; }
        public Nullable<int> COD_PROCESO { get; set; }
        public Nullable<int> COD_REGISTRO { get; set; }
        public Nullable<int> COD_ESTADO_NOMINACION_RUPS { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string NOMBRE_PROCEDIMIENTO { get; set; }
        public Nullable<int> COD_TIPO_PROCEDIMIENTO { get; set; }
        public Nullable<int> COD_AMBITO_PROCEDIMIENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CIE10 { get; set; }
        public string CIE102 { get; set; }
        public string CIE103 { get; set; }
        public Nullable<bool> ES_PROMOCION_SALUD { get; set; }
        public Nullable<bool> ES_PREVENCION_ENFERMEDAD { get; set; }
        public Nullable<bool> ES_DIAGNOSTICO { get; set; }
        public Nullable<bool> ES_TRATAMIENTO { get; set; }
        public Nullable<bool> ES_REHABILITACION { get; set; }
        public Nullable<bool> ES_PALIACION { get; set; }
        public Nullable<bool> ES_COSMETICO { get; set; }
        public string CUPS_MODIFICAR1 { get; set; }
        public string CUPS_MODIFICAR2 { get; set; }
        public string CUPS_MODIFICAR3 { get; set; }
        public string ESTRUCTURA_CUPS { get; set; }
        public string CODIGOCUPS1 { get; set; }
        public string CODIGOCUPS2 { get; set; }
        public string CODIGOCUPS3 { get; set; }
        public string CALIFICACION_AJUSTE { get; set; }
        public string CODIGO_PROPUESTO { get; set; }
        public string DESCRIPCION_PROPUESTO { get; set; }
        public string JUSTIFICACION { get; set; }
        public Nullable<bool> SE_REALIZA_ACTUALMENTE_COLOMBIA { get; set; }
        public Nullable<bool> ES_REDUCCION_MORTALIDAD { get; set; }
        public string DESCCRIPCION_REDUCCION_MORTALIDAD { get; set; }
        public Nullable<bool> ES_REDUCCION_MORBILIDAD { get; set; }
        public string DESCRIPCION_REDUCCION_MORBILIDAD { get; set; }
        public Nullable<bool> ES_REDUCCION_DISCAPCIDAD { get; set; }
        public string DESCRIPCION_REDUCCION_DISCAPACIDAD { get; set; }
        public Nullable<bool> ES_REDUCCION_INSTANCIA { get; set; }
        public string DESCRIPCION_REDUCCION_INSTANCIA { get; set; }
        public Nullable<bool> ES_DISMINUCION_COMPLICACION { get; set; }
        public string DESCRIPCION_DISMINUCION_COMPLICACION { get; set; }
        public Nullable<bool> ES_MEJORA_VIDA { get; set; }
        public string DESCRIPCION_MEJORA_VIDA { get; set; }
        public Nullable<bool> ES_OTRO { get; set; }
        public string DESCRIPCION_OTRO { get; set; }
        public Nullable<bool> CUENTA_ESTUDIOS_EFECTIVIDAD { get; set; }
        public string ARCHIVO_EFECTIVIDAD { get; set; }
        public Nullable<bool> CUENTA_ESTUDIOS_SEGURIDAD { get; set; }
        public string ARCHIVO_SEGURIDAD { get; set; }
        public Nullable<bool> TIENE_EFECTOS_ADVERSOS { get; set; }
        public string DESCRIPCION_EFECTOS_ADVERSOS { get; set; }
        public Nullable<bool> ES__INTERES_SALUD { get; set; }
        public string DESCRIPCION_INTERES_SALUD { get; set; }
        public string NOMBRE_GPC { get; set; }
        public string RECOMENDACION_GPC { get; set; }
        public Nullable<bool> ADJUNTA_ADICIONAL { get; set; }
        public string OBSERVACIONES_ADICIONAL { get; set; }
        public string ARCHIVO_ADICIONAL { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_MEDICAMENTO { get; set; }
        public string NOMBRE_RECURSO_MEDICAMENTO { get; set; }
        public string ESTADO_RECURSO_MEDICAMENTO { get; set; }
        public string REGISTRO_INVIMA_RECURSO_MEDICAMENTO { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_DISPOSITIVO { get; set; }
        public string NOMBRE_RECURSO_DISPOSITIVO { get; set; }
        public string ESTADO_RECURSO_DISPOSITIVO { get; set; }
        public string REGISTRO_INVIMA_DISPOSITIVO { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_INVITRO { get; set; }
        public string NOMBRE_RECURSO_ADICIONAL_INVITRO { get; set; }
        public string ESTADO_RECURSO_ADICIONAL_INVITRO { get; set; }
        public string REGISTRO_INVIMA_INVITRO { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_AGEBIOLOGICO { get; set; }
        public string NOMBRE_RECURSO_ADICIONAL_AGEBIOLOGICO { get; set; }
        public string ESTADO_RECURSO_ADICIONAL_AGEBIOLOGICO { get; set; }
        public string REGISTRO_INVIMA_AGEBIOLOGICO { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_BIOLOGICO { get; set; }
        public string NOMBRE_RECURSO_ADICIONAL_BIOLOGICO { get; set; }
        public string ESTADO_RECURSO_ADICIONAL_BIOLOGICO { get; set; }
        public string REGISTRO_INVIMA_BIOLOGICO { get; set; }
        public Nullable<bool> RECURSO_ADICIONAL_OTRO { get; set; }
        public string NOMBRE_RECURSO_ADICIONAL_OTRO { get; set; }
        public Nullable<bool> VULNERABLE_INFANCIA { get; set; }
        public string OBS_VULNERABLE_INFANCIA { get; set; }
        public Nullable<bool> VULNERABLE_EMBARAZO { get; set; }
        public string OBS_VULNERABLE_EMBARAZO { get; set; }
        public Nullable<bool> VULNERABLE_DESPLAZADOS { get; set; }
        public string OBS_VULNERABLE_DESPLAZADOS { get; set; }
        public Nullable<bool> VULNERABLE_ARMADO { get; set; }
        public string OBS_VULNERABLE_ARMADO { get; set; }
        public Nullable<bool> VULNERABLE_ADULTOS { get; set; }
        public string OBS_VULNERABLE_ADULTOS { get; set; }
        public Nullable<bool> VULNERABLE_DISCAPACIDAD { get; set; }
        public string OBS_VULNERABLE_DISPACAIDAD { get; set; }
        public Nullable<bool> VULNERABLE_HUERFANOS { get; set; }
        public string OBS_VULNERABLE_HUERFANOS { get; set; }
        public Nullable<bool> CONFLICTO_INTERES { get; set; }
        public string OBS_CONFLICTO_INTERES { get; set; }
        public Nullable<bool> AVALA { get; set; }
        public string OBS_AVALA { get; set; }
        public Nullable<int> COD_TIPO_JURIDICO_PROPONENTE { get; set; }
        public Nullable<bool> PROPONENTE_NATURAL { get; set; }
        public Nullable<bool> PROPONENTE_JURIDICO { get; set; }
        public string NOMBRE_PROPONENTE { get; set; }
        public string DOCUMENTO_PROPONENTE { get; set; }
        public Nullable<bool> ES_NOMBRE_PROPIO { get; set; }
        public Nullable<int> VIGENCIA { get; set; }
        public Nullable<bool> FASE_EXPERIMENTACION { get; set; }
        public string DES_PROC_NUEVO { get; set; }
        public string DES_CRITERIO_NUEVO { get; set; }
        public string DES_GRUPO_POBLACIONAL { get; set; }
        public Nullable<int> NUM_PACIENTES { get; set; }
        public Nullable<bool> REMPLAZA_PROCEDIMIENTO { get; set; }
        public string PROCEDIMIENTO_REMPLAZO { get; set; }
        public Nullable<bool> RIESGO { get; set; }
        public string DES_RIESGO { get; set; }
        public string DES_RESULTADOS { get; set; }
        public string DES_OTRAS_INTERVENCIONES { get; set; }
        public string DES_TECNOLOGIAS_EJECUCION { get; set; }
        public Nullable<bool> INVIMA1 { get; set; }
        public string DES_INVIMA1 { get; set; }
        public string NUM_INVIMA { get; set; }
        public string ESTADO_INVIMA1 { get; set; }
        public Nullable<bool> INVIMA2 { get; set; }
        public string DES_INVIMA2 { get; set; }
        public string NUM_INVIMA2 { get; set; }
        public string ESTADO_INVIMA2 { get; set; }
        public Nullable<bool> INVIMA3 { get; set; }
        public string DES_INVIMA3 { get; set; }
        public string NUM_INVIMA3 { get; set; }
        public string ESTADO_INVIMA3 { get; set; }
        public Nullable<bool> IMPLEMENTACION_TERRITORIO { get; set; }
        public string DES_IMPLEMENTACION_TERRITORIO { get; set; }
        public Nullable<bool> REALIZACION_EN_TERRITORIO { get; set; }
        public string DES_REALIZACION_EN_TERRITORIO { get; set; }
        public string CUPS_REALIZACION_EN_TERRITORIO { get; set; }
        public string YEAR_REALIZACION_EN_TERRITORIO { get; set; }
        public Nullable<bool> OTRO_SISTEMA_CODIFICACION { get; set; }
        public string DES_OTRO_SISTEMA_CODIFICACION { get; set; }
    
        public virtual AMBITO_PROCEDIMIENTO AMBITO_PROCEDIMIENTO { get; set; }
        public virtual ESTADO_NOMINACION_RUPS ESTADO_NOMINACION_RUPS { get; set; }
        public virtual PROCESO PROCESO { get; set; }
        public virtual REGISTRO REGISTRO { get; set; }
        public virtual TIPO_JURIDICO TIPO_JURIDICO { get; set; }
        public virtual TIPO_PROCEDIMIENTO TIPO_PROCEDIMIENTO { get; set; }
        public virtual VIGENCIA VIGENCIA1 { get; set; }
        public virtual ICollection<VALIDACION_PROCESO_RUPS> VALIDACION_PROCESO_RUPS { get; set; }
    }
}
