//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINACION_HUERFANA
    {
        public NOMINACION_HUERFANA()
        {
            this.ARCHIVOXNOMINACION_HUERFANA = new HashSet<ARCHIVOXNOMINACION_HUERFANA>();
        }
    
        public int COD_NOMINACION_HUERFANAS { get; set; }
        public int COD_PROCESO { get; set; }
        public int COD_REGISTRO { get; set; }
        public Nullable<bool> ES_INCLUIR { get; set; }
        public Nullable<bool> ES_EXCLUIR { get; set; }
        public Nullable<bool> ES_CAMBIO { get; set; }
        public Nullable<bool> ES_CODIGO { get; set; }
        public Nullable<bool> ES_PRUEBA { get; set; }
        public Nullable<bool> ES_DICIPLINA { get; set; }
        public Nullable<int> CONSECUTIVO_LISTADO_EFH { get; set; }
        public string NOMBRE { get; set; }
        public string CIE { get; set; }
        public string NUEVO_NOMBRE { get; set; }
        public string CIE_NUEVO_NOMBRE { get; set; }
        public string TIPO_CONFIRMACION { get; set; }
        public string CONFIRMATORIA_PROPUESTA { get; set; }
        public string CONFIRMATORIA_ACTUAL { get; set; }
        public string CUPS_CONFIRMATORIA_ACTUAL { get; set; }
        public string CONFIRMATORIA_CAMBIO_PROPUESTO { get; set; }
        public string CUPS_CONFIRMATORIA_CAMBIO_PROPUESTO { get; set; }
        public string CUPS_CONFIRMATORIA_PROPUESTA { get; set; }
        public string ALTERNA { get; set; }
        public string CUPS_ALTERNA { get; set; }
        public string ESP_ACTUAL { get; set; }
        public string ESP_ACTUAL2 { get; set; }
        public string ESP_ACTUAL3 { get; set; }
        public string ESP_ACTUAL4 { get; set; }
        public string ESP_ACTUAL5 { get; set; }
        public string ESP_PROPUESTA { get; set; }
        public string ESP_PROPUESTA2 { get; set; }
        public string ESP_PROPUESTA3 { get; set; }
        public string ESP_PROPUESTA4 { get; set; }
        public string ESP_PROPUESTA5 { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string ESPECIALIDAD2 { get; set; }
        public string ESPECIALIDAD3 { get; set; }
        public string ESPECIALIDAD4 { get; set; }
        public string ESPECIALIDAD5 { get; set; }
        public string ESPECIALIDADES_ACTUALES { get; set; }
        public string ESPECIALIDADES_PROPUESTAS_CAMBIO { get; set; }
        public string CODIGO_MODIFICAR { get; set; }
        public string CODIGO_NUEVO { get; set; }
        public string JUSTIFICACION { get; set; }
        public Nullable<bool> CONFLICTO_INTERES { get; set; }
        public string INTERES_CONFLICTO { get; set; }
        public Nullable<bool> ADJUNTA_EVIDENCIA { get; set; }
        public string RUTA_EVIDENCIA { get; set; }
        public string OBSERVACIONES_EVIDENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_NOMINACION { get; set; }
        public Nullable<decimal> COD_ESTADO_NOMINACION { get; set; }
        public string CONCEPTO_VALIDACION { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public Nullable<bool> COMPLETITUD { get; set; }
        public Nullable<bool> INCLUIDA_RESOLUCION_ACTUAL { get; set; }
        public Nullable<bool> PRUEBA_DIAGNOSTICA_ACORDE { get; set; }
        public Nullable<bool> ESPECIALIDAD_CORRESPONDE { get; set; }
        public Nullable<bool> EVIDENCIA_ADECUADA { get; set; }
        public Nullable<int> VALIDADO_POR { get; set; }
        public string OBSERVACIONES_VALIDACION { get; set; }
        public string ID_MANUAL { get; set; }
        public string NOTAS_NOMINACION { get; set; }
        public Nullable<int> VIGENCIA { get; set; }
    
        public virtual ICollection<ARCHIVOXNOMINACION_HUERFANA> ARCHIVOXNOMINACION_HUERFANA { get; set; }
    }
}
