//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINACION_PROCESO
    {
        public NOMINACION_PROCESO()
        {
            this.ARCHIVOXNOMINACION = new HashSet<ARCHIVOXNOMINACION>();
            this.OBJECION_PROCESO = new HashSet<OBJECION_PROCESO>();
            this.VALIDACION_PROCESO = new HashSet<VALIDACION_PROCESO>();
        }
    
        public int COD_NOMINACION_PROCESO { get; set; }
        public int COD_PROCESO { get; set; }
        public int COD_REGISTRO { get; set; }
        public Nullable<bool> ES_MEDICAMENTO { get; set; }
        public Nullable<bool> ES_PROCEDIMIENTO { get; set; }
        public Nullable<bool> ES_DISPOSITIVO_MEDICO { get; set; }
        public Nullable<bool> ES_SERVICIO_SALUD { get; set; }
        public Nullable<bool> ES_OTRO { get; set; }
        public string NOMBRE_TECNOLOGIA { get; set; }
        public string NOMBRE_ENFERMEDAD_CONDICION_SALUD { get; set; }
        public string OBSERVACION_TECNOLOGIA { get; set; }
        public string CIE10 { get; set; }
        public string CIE10_2 { get; set; }
        public string CIE10_INDICACION { get; set; }
        public string MEDICAMENTOS { get; set; }
        public string DISPOSITIVO { get; set; }
        public string PROCEDIMIENTO { get; set; }
        public string DESCRIPCION_OTRO { get; set; }
        public Nullable<bool> CRITERIO_A { get; set; }
        public Nullable<bool> CRITERIO_B { get; set; }
        public Nullable<bool> CRITERIO_C { get; set; }
        public Nullable<bool> CRITERIO_D { get; set; }
        public Nullable<bool> CRITERIO_E { get; set; }
        public Nullable<bool> CRITERIO_F { get; set; }
        public string OBS_CRITERIO_A { get; set; }
        public string OBS_CRITERIO_B { get; set; }
        public string OBS_CRITERIO_C { get; set; }
        public string OBS_CRITERIO_D { get; set; }
        public string OBS_CRITERIO_E { get; set; }
        public string OBS_CRITERIO_F { get; set; }
        public Nullable<bool> ADJUNTA_EVIDENCIA { get; set; }
        public string OBSERVACIONES_EVIDENCIA { get; set; }
        public string RUTA_EVIDENCIA { get; set; }
        public Nullable<bool> CONFLICTO_INTERES { get; set; }
        public string OBSERVACIONES_CONFLICTO { get; set; }
        public Nullable<System.DateTime> FECHA_NOMINACION { get; set; }
        public Nullable<int> COD_ESTADO_NOMINACION { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public Nullable<int> VALIDADO_POR { get; set; }
        public string OBSERVACIONES_VALIDACION { get; set; }
        public string ID_MANUAL { get; set; }
        public string NRO_RADICADO { get; set; }
        public string NOTAS_NOMINACION { get; set; }
        public Nullable<int> VIGENCIA { get; set; }
        public Nullable<int> ANNO_RES_EXCLUSION { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_A { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_B { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_C { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_D { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_E { get; set; }
        public Nullable<bool> EXCLUIDA_CRITERIO_F { get; set; }
    
        public virtual ICollection<ARCHIVOXNOMINACION> ARCHIVOXNOMINACION { get; set; }
        public virtual ESTADO_NOMINACION ESTADO_NOMINACION { get; set; }
        public virtual PROCESO PROCESO { get; set; }
        public virtual REGISTRO REGISTRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VIGENCIA VIGENCIA1 { get; set; }
        public virtual ICollection<OBJECION_PROCESO> OBJECION_PROCESO { get; set; }
        public virtual ICollection<VALIDACION_PROCESO> VALIDACION_PROCESO { get; set; }
    }
}
