//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINACION_PROCESO_UPC
    {
        public NOMINACION_PROCESO_UPC()
        {
            this.UPC_FORMULARIO3 = new HashSet<UPC_FORMULARIO3>();
        }
    
        public int COD_NOMINACION_PROCESO_UPC { get; set; }
        public int COD_PROCESO { get; set; }
        public Nullable<int> COD_ESTADO_NOMINACION_UPC { get; set; }
        public System.DateTime FECHA_NOMINACION { get; set; }
        public int COD_REGISTRO { get; set; }
        public string CARTA_PRESENTACION { get; set; }
        public string NOMBRE_TECNOLOGIA { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string INDICACION_USO { get; set; }
        public string JUSTIFICACION { get; set; }
        public string CIE10 { get; set; }
        public string CIE102 { get; set; }
        public string CIE103 { get; set; }
        public Nullable<bool> ES_MEDICAMENTO { get; set; }
        public Nullable<bool> ES_PROCEDIMIENTO { get; set; }
        public Nullable<bool> ES_DISPOSITIVO { get; set; }
        public Nullable<bool> ES_OTRO { get; set; }
        public Nullable<bool> ES_TITULAR_REGISTRO_TSN { get; set; }
        public string OBS_TITULAR_REGISTRO_TSN { get; set; }
        public Nullable<bool> ES_FABRICANTE_TSN { get; set; }
        public string OBS_FABRICANTE_TSN { get; set; }
        public Nullable<bool> ES_IMPORTADOR_TSN { get; set; }
        public string OBS_IMPORTADOR { get; set; }
        public Nullable<bool> ES_ACONDICIONADOR_TSN { get; set; }
        public string OBS_ACONDICIONDOR_TSN { get; set; }
        public Nullable<bool> ES_PRESTADOR_TSN { get; set; }
        public string OBS_PRESTADOR_TSN { get; set; }
        public Nullable<bool> ES_USUARIO_TSN { get; set; }
        public string OBS_USUARIO_TSN { get; set; }
        public Nullable<bool> ES_OTRO_TSN { get; set; }
        public string OBS_OTRO_TSN { get; set; }
        public string PRINCIPIO_ACTIVO { get; set; }
        public string CODIGO_ATC { get; set; }
        public string FORMA_FARMACEUTICA { get; set; }
        public string CONCENTRACION { get; set; }
        public string VIA_ADMINSITRACION { get; set; }
        public string OTRAS_INDICACIONES_MEDICAMENTO { get; set; }
        public string REGISTRO_SANITARIO { get; set; }
        public string OBSERVACIONES_MEDICAMENTO { get; set; }
        public string CODIGO_CUPS { get; set; }
        public string INDICACION_PROCEDIMIENTO { get; set; }
        public Nullable<int> COD_TIPO_PROCEDIMIENTO_UPC { get; set; }
        public string OBSERVACIONES_PROCEDIMIENTO { get; set; }
        public string REGISTRO_SANITARIO_DISPOSITIVO { get; set; }
        public Nullable<int> COD_TIPO_DISPOSITIVO { get; set; }
        public Nullable<int> COD_CLASIFICACION_RIESGO { get; set; }
        public string INDICACIONES_DISPOSITIVO { get; set; }
        public string OBSERVACIONES_DISPOSITIVO { get; set; }
        public Nullable<bool> ES_PRIMERA { get; set; }
        public string OBS_ES_PRIMERA { get; set; }
        public Nullable<bool> ES_SEGUNDA { get; set; }
        public string OBS_ES_SEGUNDA { get; set; }
        public Nullable<bool> ES_TERCERA { get; set; }
        public string OBS_ES_TERCERA { get; set; }
        public Nullable<bool> ES_COTIDIANO { get; set; }
        public string OBS_ES_COTIDIANO { get; set; }
        public Nullable<bool> ES_OTRA_IMPORTANCIA { get; set; }
        public string OBS_OTRA_IMPORTANCIA { get; set; }
        public Nullable<bool> ES_O1_MUJER { get; set; }
        public Nullable<bool> ES_O1_HOMBRE { get; set; }
        public string OBS_ES_01 { get; set; }
        public Nullable<bool> ES_1_4MUJER { get; set; }
        public Nullable<bool> ES_1_4HOMBRE { get; set; }
        public string OBS_ES_1_4 { get; set; }
        public Nullable<bool> ES_5_14_MUJER { get; set; }
        public Nullable<bool> ES_5_14_HOMBRE { get; set; }
        public string ES_5_14_OBS { get; set; }
        public Nullable<bool> ES_15_18_MUJER { get; set; }
        public Nullable<bool> ES_15_18_HOMBRE { get; set; }
        public string ES_15_18_OBS { get; set; }
        public Nullable<bool> ES_19_29_MUJER { get; set; }
        public Nullable<bool> ES_19_29_HOMBRE { get; set; }
        public string ES_19_29_OBS { get; set; }
        public Nullable<bool> ES_30_44_MUJER { get; set; }
        public Nullable<bool> ES_30_44_HOMBRE { get; set; }
        public string ES_30_44_OBS { get; set; }
        public Nullable<bool> ES_45_59_MUJER { get; set; }
        public Nullable<bool> ES_45_59_HOMBRE { get; set; }
        public string ES_45_59_OBS { get; set; }
        public Nullable<bool> ES_60_69_MUJER { get; set; }
        public Nullable<bool> ES_60_69_HOMBRE { get; set; }
        public string ES_60_69_OBS { get; set; }
        public Nullable<bool> ES_70_79_MUJER { get; set; }
        public Nullable<bool> ES_70_79_HOMBRE { get; set; }
        public string ES_70_79_OBS { get; set; }
        public Nullable<bool> ES_80_100_MUJER { get; set; }
        public Nullable<bool> ES_80_100_HOMBRE { get; set; }
        public string ES_80_100_OBS { get; set; }
        public Nullable<bool> ES_PROMOCION_SALUD { get; set; }
        public string OBS_ES_PROMOCION_SALUD { get; set; }
        public Nullable<bool> ES_PREVENCION_ENFERMEDAD { get; set; }
        public string OBS_ES_PREVENCION_ENFERMEDAD { get; set; }
        public Nullable<bool> ES_DIAGNOSTICO { get; set; }
        public string OBS_ES_DIAGNOSTICO { get; set; }
        public Nullable<bool> ES_TRATAMIENTO { get; set; }
        public string OBS_ES_TRATAMIENTO { get; set; }
        public Nullable<bool> ES_REHABILITACION { get; set; }
        public string OBS_ES_REHABILITACION { get; set; }
        public Nullable<bool> ES_PALIACION { get; set; }
        public string OBS_ES_PALIACION { get; set; }
        public Nullable<bool> ES_COSMETICO { get; set; }
        public string OBS_ES_COSEMTICO { get; set; }
        public Nullable<int> COD_AMBITO_UPC { get; set; }
        public Nullable<bool> ES_REDUCCION_MORTALIDAD { get; set; }
        public string OBS_ES_REDUCCION_MORTALIDAD { get; set; }
        public Nullable<bool> ES_REDUCCION_MORBILIDAD { get; set; }
        public string OBS_ES_REDUCCION_MORBILIDAD { get; set; }
        public Nullable<bool> ES_DISMINUCION_INSTANCIA { get; set; }
        public string OBS_ES_DISMINUCION_INSTANCIA { get; set; }
        public Nullable<bool> ES_MEJORA_CALIDAD_VIDA { get; set; }
        public string OBS_ES_MEJORA_CALIDAD_VIDA { get; set; }
        public Nullable<bool> ES_OTRO_USO_TENOCLOGIA { get; set; }
        public string OBS_ES_OTRO_USO_TECNOLOGIA { get; set; }
        public Nullable<bool> TIENE_EFECTIVIDAD { get; set; }
        public string ARCHIVO_EFECTIVIDAD { get; set; }
        public Nullable<bool> TIENE_SEGURIDAD { get; set; }
        public string ARCHIVO_SEGURIDAD { get; set; }
        public Nullable<bool> TIENE_EFICACIA { get; set; }
        public string ARCHIVO_EFICACIA { get; set; }
        public Nullable<bool> OTRA_EVIDENCIA { get; set; }
        public string OBS_OTRA_EVIDENCIA { get; set; }
        public Nullable<bool> ES_EXTERIOR { get; set; }
        public string OBS_ES_EXTERIOR { get; set; }
        public string NOMBRE_GPC { get; set; }
        public string RECOMENDACION_GPC { get; set; }
        public Nullable<bool> PRIMERA_INFANCIA { get; set; }
        public string OBS_PRIMERA_INFANACIA { get; set; }
        public Nullable<bool> EMBARAZO { get; set; }
        public string OBS_EMBARAZO { get; set; }
        public Nullable<bool> DESPLAZADOS { get; set; }
        public string OBS_DESPLAZADOS { get; set; }
        public Nullable<bool> VICTIMAS_ARMADAS { get; set; }
        public string OBS_VICTIMAS_ARMADAS { get; set; }
        public Nullable<bool> ADULTOS_MAYORES { get; set; }
        public string OBS_ADULTOS_MAYORES { get; set; }
        public Nullable<bool> DISCAPACIDAD { get; set; }
        public string OBS_DISCAPACIDAD { get; set; }
        public Nullable<bool> ENF_HUERFANADAS { get; set; }
        public string OBS_ENF_HUERFANAS { get; set; }
        public Nullable<bool> ES_SALUD_PUBLICA { get; set; }
        public string OBS_SALUD_PUBLICA { get; set; }
        public Nullable<bool> ES_RECURSO_MEDICAMENTO { get; set; }
        public string OBS_ES_RECURSO_MEDICAMENTO { get; set; }
        public Nullable<bool> ES_RECURSO_DISPOSITIVO { get; set; }
        public string OBS_ES_RECURSO_DISPOSITIVO { get; set; }
        public Nullable<bool> ES_RECURSO_INVITRO { get; set; }
        public string OBS_ES_RECURSO_INVITRO { get; set; }
        public Nullable<bool> ES_AGENTE_BIOLOGICO { get; set; }
        public string OBS_ES_AGENTE_BIOLOGICO { get; set; }
        public Nullable<bool> ES_PRODCUTO_BIOLOGICO { get; set; }
        public string OBS_ES_PRODCUTO_BIOLOGICO { get; set; }
        public Nullable<bool> ES_OTRO_RECURSO_ADICIONAL { get; set; }
        public string OBS_ES_OTRO_RECURSO_ADICIONAL { get; set; }
        public string NOMBRE_COMPARADOR { get; set; }
        public string CODIGO_ATC_COMPARADOR { get; set; }
        public string COBERTURA { get; set; }
        public Nullable<bool> ADJUNTA_EVIDENCIA { get; set; }
        public string OBS_EVIDENCIA { get; set; }
        public string ARCHIVO_EVIDENCIA { get; set; }
        public Nullable<bool> CONFLICTO_SI { get; set; }
        public string OBS_CONFLICTO { get; set; }
        public string URL_FORMATO3 { get; set; }
        public string ULR_FORMATO4 { get; set; }
        public string URL_FORMATO5 { get; set; }
        public Nullable<bool> NOMINACION_VALIDA { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public Nullable<int> VALIDADA_POR { get; set; }
        public string OBSERVACIONES_VALIDACION { get; set; }
    
        public virtual AMBITO_UPC AMBITO_UPC { get; set; }
        public virtual CLASIFICACION_RIESGO CLASIFICACION_RIESGO { get; set; }
        public virtual ESTADO_NOMINACION_UPC ESTADO_NOMINACION_UPC { get; set; }
        public virtual REGISTRO REGISTRO { get; set; }
        public virtual TIPO_DISPOSITIVO TIPO_DISPOSITIVO { get; set; }
        public virtual TIPO_PROCEDIMIENTO TIPO_PROCEDIMIENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<UPC_FORMULARIO3> UPC_FORMULARIO3 { get; set; }
        public virtual PROCESO PROCESO { get; set; }
    }
}
