//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECION_HUERFANA
    {
        public OBJECION_HUERFANA()
        {
            this.ARCHIVOXOBJECION_HUERFANA = new HashSet<ARCHIVOXOBJECION_HUERFANA>();
        }
    
        public int COD_OBJECION_HUERFANA { get; set; }
        public Nullable<int> COD_NOMINACION_HUERFANA { get; set; }
        public Nullable<int> COD_REGISTRO { get; set; }
        public string OBSERVACIONES_OBJECION { get; set; }
        public Nullable<System.DateTime> FECHA_OBJECION { get; set; }
    
        public virtual ICollection<ARCHIVOXOBJECION_HUERFANA> ARCHIVOXOBJECION_HUERFANA { get; set; }
    }
}
