//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaSecreta
    {
        public PreguntaSecreta()
        {
            this.Participante = new HashSet<Participante>();
            this.REGISTRO = new HashSet<REGISTRO>();
        }
    
        public short Id { get; set; }
        public string TextoPregunta { get; set; }
    
        public virtual ICollection<Participante> Participante { get; set; }
        public virtual ICollection<REGISTRO> REGISTRO { get; set; }
    }
}
