//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO
    {
        public PROCESO()
        {
            this.ARCHIVOXPROCESO = new HashSet<ARCHIVOXPROCESO>();
            this.EVENTO = new HashSet<EVENTO>();
            this.NOMINACION_PROCESO_UPC = new HashSet<NOMINACION_PROCESO_UPC>();
            this.TECNOLOGIA = new HashSet<TECNOLOGIA>();
            this.VIGENCIA = new HashSet<VIGENCIA>();
            this.NOMINACION_PROCESO_RUPS = new HashSet<NOMINACION_PROCESO_RUPS>();
            this.NOMINACION_PROCESO = new HashSet<NOMINACION_PROCESO>();
        }
    
        public int COD_PROCESO { get; set; }
        public string NOMBRE_PROCESO { get; set; }
        public string TEXTO_DIRIGIDO_A { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_NOMINACION { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_NOMINACION { get; set; }
        public string OBSERVACIONES_PROCESO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_NOMINACION2 { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_NOMINACION2 { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_NOMINACION3 { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_NOMINACION3 { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_NOMINACION4 { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_NOMINACION4 { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_OBJECION { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_OBJECION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_OBJECION2 { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_OBJECION2 { get; set; }
        public Nullable<bool> ACTIVO_PARTICIPAR { get; set; }
        public Nullable<bool> ACTIVO_RESULTADOS { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_PRIMERA_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_PRIMERA_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_SEGUNDA_VIGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_SEGUNDA_VIGENCIA { get; set; }
        public Nullable<bool> ES_RUPS { get; set; }
        public string URL_ACTIVO_PARTICIPAR { get; set; }
        public Nullable<int> VIGENCIAS { get; set; }
        public Nullable<bool> ES_UPC { get; set; }
        public Nullable<bool> ES_HUERFANA { get; set; }
        public Nullable<bool> ES_AAA { get; set; }
    
        public virtual ICollection<ARCHIVOXPROCESO> ARCHIVOXPROCESO { get; set; }
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual ICollection<NOMINACION_PROCESO_UPC> NOMINACION_PROCESO_UPC { get; set; }
        public virtual ICollection<TECNOLOGIA> TECNOLOGIA { get; set; }
        public virtual ICollection<VIGENCIA> VIGENCIA { get; set; }
        public virtual ICollection<NOMINACION_PROCESO_RUPS> NOMINACION_PROCESO_RUPS { get; set; }
        public virtual ICollection<NOMINACION_PROCESO> NOMINACION_PROCESO { get; set; }
    }
}
