//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public REGISTRO()
        {
            this.CONFIRMACION_EVENTO = new HashSet<CONFIRMACION_EVENTO>();
            this.NOMINACION_PROCESO_UPC = new HashSet<NOMINACION_PROCESO_UPC>();
            this.OBJECION_PROCESO = new HashSet<OBJECION_PROCESO>();
            this.REGISTRO1 = new HashSet<REGISTRO>();
            this.TipoUsuario = new HashSet<TipoUsuario>();
            this.NOMINACION_PROCESO_RUPS = new HashSet<NOMINACION_PROCESO_RUPS>();
            this.NOMINACION_PROCESO = new HashSet<NOMINACION_PROCESO>();
        }
    
        public int COD_REGISTRO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public bool ES_PERSONA_NATURAL { get; set; }
        public bool ES_PERSONA_JURIDICA { get; set; }
        public Nullable<int> COD_TIPO_JURIDICO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> COD_SEXO { get; set; }
        public Nullable<int> COD_POBLACION_ESPECIAL { get; set; }
        public Nullable<int> COD_NIVEL_FORMACION { get; set; }
        public short COD_TIPO_IDENTIFICACION { get; set; }
        public string DOCUMENTO { get; set; }
        public string DIGITO_VERIFICACION { get; set; }
        public string FECHA_ACTA { get; set; }
        public short COD_MUNICIPIO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> COD_TIPO_ZONA { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
        public string CORREO_ALTERNO { get; set; }
        public Nullable<short> COD_PREGUNTA_SECRETA { get; set; }
        public string RESPUESTA_PREGUNTA_SECRETA { get; set; }
        public string RUTA_ARCHIVO { get; set; }
        public Nullable<int> COD_REGISTRO_PADRE { get; set; }
        public Nullable<bool> AUTORIZO { get; set; }
        public Nullable<bool> CERTIFICO { get; set; }
        public Nullable<bool> TERMINOS { get; set; }
        public string FACULTAD { get; set; }
        public string ESPECIALIDAD { get; set; }
        public Nullable<int> REPRESENTADOS { get; set; }
        public Nullable<int> COD_TIPO_REPRESENTADO { get; set; }
        public Nullable<int> COD_TIPO_IPS { get; set; }
        public string CONTRASENA { get; set; }
        public Nullable<System.DateTime> FECHA_VERIFICACION_CORREO { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public Nullable<int> VALIDADO_POR { get; set; }
        public string SOLICITUD_ACLARACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD_ACLARACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO_ACLARACIONES { get; set; }
        public Nullable<int> ACLARACIONES_SOLICITADAS_POR { get; set; }
        public Nullable<int> COD_ESTADO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_RETIRO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
    
        public virtual ICollection<CONFIRMACION_EVENTO> CONFIRMACION_EVENTO { get; set; }
        public virtual ESTADO_REGISTRO ESTADO_REGISTRO { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual NIVEL_FORMACION NIVEL_FORMACION { get; set; }
        public virtual ICollection<NOMINACION_PROCESO_UPC> NOMINACION_PROCESO_UPC { get; set; }
        public virtual ICollection<OBJECION_PROCESO> OBJECION_PROCESO { get; set; }
        public virtual POBLACION_ESPECIAL POBLACION_ESPECIAL { get; set; }
        public virtual PreguntaSecreta PreguntaSecreta { get; set; }
        public virtual ICollection<REGISTRO> REGISTRO1 { get; set; }
        public virtual REGISTRO REGISTRO2 { get; set; }
        public virtual SEXO SEXO { get; set; }
        public virtual TIPO_IPS TIPO_IPS { get; set; }
        public virtual TIPO_JURIDICO TIPO_JURIDICO { get; set; }
        public virtual TIPO_REPRESENTADO TIPO_REPRESENTADO { get; set; }
        public virtual TIPO_ZONA TIPO_ZONA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual ICollection<TipoUsuario> TipoUsuario { get; set; }
        public virtual ICollection<NOMINACION_PROCESO_RUPS> NOMINACION_PROCESO_RUPS { get; set; }
        public virtual ICollection<NOMINACION_PROCESO> NOMINACION_PROCESO { get; set; }
    }
}
