//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPOSITORIO_HUEFANAS
    {
        public int ID { get; set; }
        public string SECCION { get; set; }
        public string URL_ARCHIVO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ANNO { get; set; }
    }
}
