//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNOLOGIA
    {
        public TECNOLOGIA()
        {
            this.TECNOLOGIASXEVENTO = new HashSet<TECNOLOGIASXEVENTO>();
            this.TECNOLOGIAXCONFIRMACION_EVENTO = new HashSet<TECNOLOGIAXCONFIRMACION_EVENTO>();
        }
    
        public Nullable<int> COD_PROCESO { get; set; }
        public int COD_TECNOLOGIA { get; set; }
        public string NOMBRE_TECNOLOGIA { get; set; }
    
        public virtual ICollection<TECNOLOGIASXEVENTO> TECNOLOGIASXEVENTO { get; set; }
        public virtual ICollection<TECNOLOGIAXCONFIRMACION_EVENTO> TECNOLOGIAXCONFIRMACION_EVENTO { get; set; }
        public virtual PROCESO PROCESO { get; set; }
    }
}
