//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNOLOGIASXEVENTO
    {
        public int COD_TECNOLOGIAXEVENTO { get; set; }
        public Nullable<int> COD_EVENTO { get; set; }
        public Nullable<int> COD_TECNOLOGIA { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual TECNOLOGIA TECNOLOGIA { get; set; }
    }
}
