//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMATICA_EVENTO
    {
        public TEMATICA_EVENTO()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int COD_TEMATICA_EVENTO { get; set; }
        public string NOMBRE_TEMATICA { get; set; }
    
        public virtual ICollection<EVENTO> EVENTO { get; set; }
    }
}
