//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_JURIDICOXEVENTO
    {
        public Nullable<int> COD_TIPO_JURIDICO { get; set; }
        public Nullable<int> COD_EVENTO { get; set; }
        public int COD_TIPO_JURIDICOXEVENTO { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual TIPO_JURIDICO TIPO_JURIDICO { get; set; }
    }
}
