//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIdentificacion
    {
        public TipoIdentificacion()
        {
            this.Participante = new HashSet<Participante>();
            this.Participante1 = new HashSet<Participante>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> EsPersona { get; set; }
        public Nullable<bool> EsActa { get; set; }
    
        public virtual ICollection<Participante> Participante { get; set; }
        public virtual ICollection<Participante> Participante1 { get; set; }
    }
}
