//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            this.Participante = new HashSet<Participante>();
            this.REGISTRO = new HashSet<REGISTRO>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> ES_NATURAL { get; set; }
        public Nullable<bool> ES_JURIDICA { get; set; }
        public Nullable<bool> ES_NUEVO { get; set; }
        public Nullable<bool> ES_AGREMIADO { get; set; }
        public Nullable<bool> ES_IPS { get; set; }
    
        public virtual ICollection<Participante> Participante { get; set; }
        public virtual ICollection<REGISTRO> REGISTRO { get; set; }
    }
}
