//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_JURIDICO
    {
        public TIPO_JURIDICO()
        {
            this.REGISTRO = new HashSet<REGISTRO>();
            this.TIPO_JURIDICOXEVENTO = new HashSet<TIPO_JURIDICOXEVENTO>();
            this.NOMINACION_PROCESO_RUPS = new HashSet<NOMINACION_PROCESO_RUPS>();
        }
    
        public int COD_TIPO_JURIDICO { get; set; }
        public string NOMBRE_TIPO_JURIDICO { get; set; }
        public Nullable<int> PADRE { get; set; }
    
        public virtual ICollection<REGISTRO> REGISTRO { get; set; }
        public virtual ICollection<TIPO_JURIDICOXEVENTO> TIPO_JURIDICOXEVENTO { get; set; }
        public virtual ICollection<NOMINACION_PROCESO_RUPS> NOMINACION_PROCESO_RUPS { get; set; }
    }
}
