//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPC_FORMULARIO3
    {
        public int COD_UPC_FORMULARIO3 { get; set; }
        public int COD_NOMINACION_PROCESO_UPC { get; set; }
        public Nullable<int> COD_TIPO_NOMINACION_MEDICAMENTO { get; set; }
        public string OBS_TIPO_NOMINACION_MEDICAMENTO { get; set; }
        public string NumCasasFarmaceuticas { get; set; }
        public string NumAnosMedicamento { get; set; }
        public string CodCumMedicamento { get; set; }
        public string DosisPediatraMedicamentos { get; set; }
        public string DosisAdultosMedicamentos { get; set; }
        public string IndicacionMedicamento { get; set; }
        public string PrecioPorFormaFarma { get; set; }
        public string PrecioPorConcentracion { get; set; }
        public string PrecioPorPresentacion { get; set; }
        public string ValorCOPMedicamento { get; set; }
        public string UnidadMedidaMedicamento { get; set; }
        public Nullable<bool> ReaccionesAdversasSI { get; set; }
        public string OBSReaccionesAdversas { get; set; }
        public Nullable<bool> Contraindicaciones { get; set; }
        public string OBSContraindicaciones { get; set; }
        public Nullable<bool> AdvertenciasPrecauciones { get; set; }
        public string OSBAdvertenciasPrecauciones { get; set; }
        public Nullable<bool> Interacciones { get; set; }
        public string OBSInteracciones { get; set; }
        public Nullable<bool> Interrupcion { get; set; }
        public string OSBInterrupcion { get; set; }
        public Nullable<bool> ListadoEscencialesSi { get; set; }
        public string ObservacionesListadoEscencial { get; set; }
        public string NombreGPCMedicamento { get; set; }
        public string RecomendacionMedicamentoGPC { get; set; }
        public string GradoRecomendacionMedicamentoGPC { get; set; }
        public Nullable<bool> NuevoProcedimientoSi { get; set; }
        public string ObservacionesNuevoProcedimiento { get; set; }
        public string IpsREalizanProcedimiento { get; set; }
        public string NumAnosProcedimento { get; set; }
        public string FrecuenciaProcedimiento { get; set; }
        public string FrecuenciaAplicacionProcedimiento { get; set; }
        public string DuracionProcedimiento { get; set; }
        public string PrecioDuracionProcedimiento { get; set; }
        public string NombreGPCProcedimiento { get; set; }
        public string RecomendacionProcedimientoGPC { get; set; }
        public string GradoRecomendacionProcedimientoGPC { get; set; }
        public string desenlacesProcedimiento { get; set; }
        public string ResultadosSeguridadProcedimiento { get; set; }
        public string TamanoPoblacion { get; set; }
        public string TamanoPoblacionColombiana { get; set; }
        public string RElacionTsnCArgaEnfermedad { get; set; }
        public string Beneficios { get; set; }
        public Nullable<bool> TSNReduceMortalidadSi { get; set; }
        public string OBSTSNReduceMortalidad { get; set; }
        public Nullable<bool> TSNMejoraDiscapacidadSi { get; set; }
        public string OBSTSNMejoraDiscapacidadSi { get; set; }
    
        public virtual NOMINACION_PROCESO_UPC NOMINACION_PROCESO_UPC { get; set; }
        public virtual TIPO_NOMINACION_MEDICAMENTO TIPO_NOMINACION_MEDICAMENTO { get; set; }
    }
}
