//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDACION_PROCESO_RUPS
    {
        public int COD_VALIDACION_PROESO_RUPS { get; set; }
        public Nullable<int> COD_NOMINACION_PROCESO_RUPS { get; set; }
        public Nullable<int> VALIDADA_POR { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public string VALIDACION_VALIDADOR { get; set; }
        public string VALIDACION_NOMBRE_PROCEDIMIENTO { get; set; }
        public string VALIDACION_TIPO_PROCEDIMIENTO { get; set; }
        public string VALIDACION_AMBITO_USO { get; set; }
        public string VALIDACION_DESCRIPCION { get; set; }
        public string VALIDACION_CIE10 { get; set; }
        public string VALIDACION_FINALIDAD_PROCEDIMIENTO { get; set; }
        public string VALIDACION_PROPUESTA_AJUSTE { get; set; }
        public string VALIDACION_JUSTIFICACION { get; set; }
        public string VALIDACION_TERITORIO_NACIONAL { get; set; }
        public string VALIDACION_REDUCCION_MORTALIDAD { get; set; }
        public string VALIDACION_REDUCCION_MORBILIDAD { get; set; }
        public string VALIDACION_REDUCCION_DISCAPACIDAD { get; set; }
        public string VALIDACION_REDUCCION_ESTANCIA_HOS { get; set; }
        public string VALIDACION_REDUCION_COMPLICACION { get; set; }
        public string VALIDACION_MEJORA_VIDA { get; set; }
        public string VALIDACION_MEJORA_OTRO { get; set; }
        public string VALIDACION_EFECTIVIDAD_CLINICA { get; set; }
        public string VALIDACION_ESTUDIOS_SEGURIDAD { get; set; }
        public string VALIDACION_RIESGOS_ADVERSOS { get; set; }
        public string VALIDACION_INTERES_SALUD_PUBLICA { get; set; }
        public string VALIDACION_GPC { get; set; }
        public string VALIDACION_INFO_ADICIONAL { get; set; }
        public string VALIDACION_MEDICAMENTO_ADICIONAL { get; set; }
        public string VALIDACION_DISPOSITIVO_ADICIONAL { get; set; }
        public string VALIDACION_INVITRO_ADICIONAL { get; set; }
        public string VALIDACION_AGENTE_BIOLOGICO { get; set; }
        public string VALIDACION_PRODUCTO_BIOLOGICO { get; set; }
        public string VALIDACION_OTRO { get; set; }
        public string VALIDACION_VULNERABILIDAD { get; set; }
        public string VALIDACION_CONFLICTO { get; set; }
        public string VALIDACION_AVALA { get; set; }
        public Nullable<bool> NOMINACION_VALIDA { get; set; }
        public string OBSERVACIONES_VALIDACION { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual NOMINACION_PROCESO_RUPS NOMINACION_PROCESO_RUPS { get; set; }
    }
}
