//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioInscripcionMinSalud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDACION_PROCESO
    {
        public VALIDACION_PROCESO()
        {
            this.DETALLE_VALIDACION_PROCESO = new HashSet<DETALLE_VALIDACION_PROCESO>();
        }
    
        public int COD_VALIDACION_PROCESO { get; set; }
        public Nullable<int> COD_NOMINACION_PROCESO { get; set; }
        public Nullable<System.DateTime> FECHA_VALIDACION { get; set; }
        public Nullable<int> VALIDADO_POR { get; set; }
        public string OBSERVACIONES_GENERALES { get; set; }
    
        public virtual ICollection<DETALLE_VALIDACION_PROCESO> DETALLE_VALIDACION_PROCESO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual NOMINACION_PROCESO NOMINACION_PROCESO { get; set; }
    }
}
