-- Habilitar la inserci�n de valores en una columna IDENTITY
SET IDENTITY_INSERT EXCLUSIONES.IndicacionExclusion ON;

INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (1,1,N'EXCLUÍDO EN DOLOR NEUROPÁTICO (Con sus diagnósticos CIE-10 relacionados)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (2,2,N'EXCLUÍDO EN DOLOR NEUROPÁTICO (Con sus diagnósticos CIE-10 relacionados)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (3,3,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (4,4,N'TODAS LAS INDICACIONES Aclaración: LOS ALIMENTOS CON PROPÓSITO MÉDICO ESPECIAL, NO HACEN PARTE DE ESTA EXCLUSIÓN.');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (5,5,N'ARTRITIS REUMATOIDE');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (6,6,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (7,6,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (8,7,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (9,7,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (10,8,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (11,8,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (12,9,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (13,9,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (14,10,N'EXCLUÍDO EN DOLOR NEUROPÁTICO (Con sus diagnósticos CIE-10 relacionados)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (15,11,N'MANEJO DEL DOLOR EN GENERAL');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (16,11,N'FATIGA CRÓNICA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (17,11,N'CÁNCER');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (18,12,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (19,13,N'CEGUERA BINOCULAR');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (20,14,N'CEGUERA BINOCULAR');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (21,15,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (22,16,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (23,17,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (24,18,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (25,19,N'(ÓSTEO)ARTROSIS PRIMARIA GENERALIZADA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (26,19,N'OTRAS POLIARTROSIS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (27,19,N'ARTROSIS PRIMARIA DE OTRAS ARTICULACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (28,20,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (29,21,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (30,22,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (31,23,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (32,24,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (33,25,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (34,26,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (35,27,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (36,28,N'ECLAMPSIA EN EL EMBARAZO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (37,29,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (38,30,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (39,31,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (40,32,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (41,33,N'EXCLUIDO EN CÁNCER PULMONAR NO MICROCÍTICO SIN EGFR (Con sus diagnósticos CIE-10 relacionados).');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (42,34,N'G800 PARÁLISIS CEREBRAL ESPÁSTICA CUADRIPLÉJICA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (43,34,N'G822 PARAPLEJIA, NO ESPECIFICADA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (44,34,N'R263 INMOVILIDAD');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (45,34,N'M199 ARTROSIS, NO ESPECIFICADA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (46,35,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (47,36,N'N979 - INFERTILIDAD FEMENINA, NO ESPECIFICADA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (48,37,N'BLEFAROPLASTIA ESTÉTICA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (49,37,N'RINOPLASTIA ESTÉTICA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (50,37,N'OTROS PROCEDIMIENTOS ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (51,38,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (52,39,N'CON FINES ESTETICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (53,40,N'TODAS Aclaración: LA GLUCOSAMINA SULFATO, NO HACE PARTE DE ESTA EXCLUSIÓN.');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (54,41,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (55,42,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (56,42,N'HIPOPLASIA GLÚTEO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (57,43,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (58,43,N'HIPOPLASIA GLÚTEO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (59,44,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (60,45,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (61,46,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (62,47,N'EXCLUIDO EN ARTRITIS IDIOPÁTICA JUVENIL (Con sus diagnósticos CIE-10 relacionados)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (63,48,N'N979 - INFERTILIDAD FEMENINA, NO ESPECIFICADA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (64,49,N'N46 - ESTERILIDAD EN EL VARÓN');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (65,50,N'PARA EL CUIDADO AMBULATORIO ');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (66,51,N'EXCLUIDO EN ESCLEROSIS MÚLTIPLE TIPO SECUNDARIA PROGRESIVA (Con sus diagnósticos CIE-10 relacionados)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (67,52,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (68,53,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (69,54,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (70,55,N'CEGUERA BINOCULAR');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (71,56,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (72,56,N'HIPOPLASIA MAMARIA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (73,57,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (74,57,N'HIPOPLASIA MAMARIA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (75,58,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (76,59,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (77,60,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (78,61,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (79,62,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (80,63,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (81,64,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (82,65,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (83,65,N'PTOSIS MAMARIA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (84,66,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (85,67,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (86,68,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (87,69,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (88,70,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (89,71,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (90,72,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (91,73,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (92,74,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (93,75,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (94,75,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (95,76,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (96,76,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (97,77,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (98,77,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (99,78,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (100,79,N'LIPODISTROFIA ABDOMINAL');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (101,79,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (102,80,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (103,81,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (104,82,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (105,83,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (106,84,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (107,85,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (108,86,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (109,87,N'DERMATITIS ALÉRGICA DE CONTACTO DEBIDA A OTROS AGENTES (L238)');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (110,88,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (111,89,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (112,90,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (113,91,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (114,92,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (115,93,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (116,94,N'ALTERACION ESTÉTICA DE LA NARIZ INDEPENDIENTE DE LA VÍA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (117,95,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (118,95,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (119,96,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (120,96,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (121,97,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (122,97,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (123,98,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (124,98,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (125,99,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (126,99,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (127,100,N'BLEFAROPTOSIS POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (128,100,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (129,101,N'CON FINES ESTÉTICOS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (130,101,N'POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (131,102,N'RITIDOSIS FACIAL POR ENVEJECIMIENTO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (132,103,N'R521 DOLOR CRÓNICO INTRATABLE');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (133,104,N'OSTEOPOROSIS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (134,104,N'OSTEOARTROSIS DEGENERATIVA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (135,104,N'ARTRITIS REUMATOIDEA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (136,104,N'CÁNCER');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (137,104,N'COLESTEROL ELEVADO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (138,104,N'HIPERTENSIÓN ARTERIAL');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (139,104,N'JAQUECAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (140,104,N'INSOMNIO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (141,104,N'DEPRESIÓN');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (142,104,N'GASTRITIS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (143,104,N'TABAQUISMO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (144,104,N'COLON IRRITABLE');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (145,104,N'PARÁLISIS FACIAL');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (146,104,N'ALCOHOLISMO');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (147,104,N'ASMA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (148,104,N'FOBIAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (149,104,N'HERNIA DISCAL');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (150,104,N'DOLORES MUSCULARES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (151,105,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (152,106,N'TODAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (153,107,N'PARA PERSONAS SANAS');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (154,108,N'CEGUERA BINOCULAR');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (155,109,N'ENFERMEDAD PULMONAR OBSTRUCTIVA CRÓNICA COMO MONOTERAPIA');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (156,110,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (157,111,N'F840 - AUTISMO EN LA NIÑEZ');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (158,112,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (159,113,N'TODAS LAS INDICACIONES');
INSERT INTO EXCLUSIONES.IndicacionExclusion(id,IdTecnoIogiaExcluida,Descripcion) VALUES (160,114,N'TODAS LAS INDICACIONES');


-- Desactivar la inserci�n de valores en una columna IDENTITY
SET IDENTITY_INSERT EXCLUSIONES.IndicacionExclusion OFF;